[package]
name = "ThoughtfulAI"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.128"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"